// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearConfig() {
  return window['go']['main']['App']['ClearConfig']();
}

export function DeleteAllowed() {
  return window['go']['main']['App']['DeleteAllowed']();
}

export function DeleteObjects(arg1, arg2) {
  return window['go']['main']['App']['DeleteObjects'](arg1, arg2);
}

export function DeletePrefix(arg1, arg2) {
  return window['go']['main']['App']['DeletePrefix'](arg1, arg2);
}

export function DownloadObject(arg1, arg2) {
  return window['go']['main']['App']['DownloadObject'](arg1, arg2);
}

export function DownloadObjects(arg1, arg2) {
  return window['go']['main']['App']['DownloadObjects'](arg1, arg2);
}

export function EstimatePrefixes(arg1, arg2) {
  return window['go']['main']['App']['EstimatePrefixes'](arg1, arg2);
}

export function GetBucketStats(arg1) {
  return window['go']['main']['App']['GetBucketStats'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDownloadConcurrency() {
  return window['go']['main']['App']['GetDownloadConcurrency']();
}

export function HasConfig() {
  return window['go']['main']['App']['HasConfig']();
}

export function ListBuckets() {
  return window['go']['main']['App']['ListBuckets']();
}

export function ListObjects(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListObjects'](arg1, arg2, arg3);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function PreviewObject(arg1, arg2) {
  return window['go']['main']['App']['PreviewObject'](arg1, arg2);
}

export function SaveConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3, arg4);
}

export function SearchObjects(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchObjects'](arg1, arg2, arg3);
}

export function SetDeleteEnabled(arg1) {
  return window['go']['main']['App']['SetDeleteEnabled'](arg1);
}

export function SetDownloadConcurrency(arg1) {
  return window['go']['main']['App']['SetDownloadConcurrency'](arg1);
}

export function SetInlinePreviews(arg1) {
  return window['go']['main']['App']['SetInlinePreviews'](arg1);
}

export function SetPreviewSizeLimit(arg1) {
  return window['go']['main']['App']['SetPreviewSizeLimit'](arg1);
}

export function SetViewMode(arg1) {
  return window['go']['main']['App']['SetViewMode'](arg1);
}

export function TestConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3);
}

export function UploadObject(arg1, arg2) {
  return window['go']['main']['App']['UploadObject'](arg1, arg2);
}

export function UploadObjects(arg1, arg2) {
  return window['go']['main']['App']['UploadObjects'](arg1, arg2);
}
