// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearConfig():Promise<void>;

export function DeleteAllowed():Promise<boolean>;

export function DeleteObjects(arg1:string,arg2:Array<string>):Promise<void>;

export function DeletePrefix(arg1:string,arg2:string):Promise<void>;

export function DownloadObject(arg1:string,arg2:string):Promise<void>;

export function DownloadObjects(arg1:string,arg2:Array<string>):Promise<void>;

export function EstimatePrefixes(arg1:string,arg2:Array<string>):Promise<main.PrefixEstimate>;

export function GetBucketStats(arg1:string):Promise<main.BucketStats>;

export function GetConfig():Promise<main.Config>;

export function GetDownloadConcurrency():Promise<number|number>;

export function HasConfig():Promise<boolean>;

export function ListBuckets():Promise<Array<main.BucketInfo>>;

export function ListObjects(arg1:string,arg2:string,arg3:string):Promise<main.ListResult>;

export function LoadConfig():Promise<void>;

export function PreviewObject(arg1:string,arg2:string):Promise<main.PreviewPayload>;

export function SaveConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SearchObjects(arg1:string,arg2:string,arg3:string):Promise<Array<main.ObjectInfo>>;

export function SetDeleteEnabled(arg1:boolean):Promise<void>;

export function SetDownloadConcurrency(arg1:number):Promise<void>;

export function SetInlinePreviews(arg1:boolean):Promise<void>;

export function SetPreviewSizeLimit(arg1:number):Promise<void>;

export function SetViewMode(arg1:string):Promise<void>;

export function TestConnection(arg1:string,arg2:string,arg3:string):Promise<void>;
